export enum EActionTypes {
  LOAD_RESULTS_REQUEST = 'MAIN/LOAD_RESULTS_REQUEST',
  LOAD_RESULTS_SUCCESS = 'MAIN/LOAD_RESULTS_SUCCESS',
  LOAD_RESULTS_FAILURE = 'MAIN/LOAD_RESULTS_FAILURE',

  SET_TASK_IDS = 'MAIN/SET_TASK_IDS',
  SET_TASK_STATUS = 'MAIN/SET_TASK_STATUS',
  SET_SEARCH_QUERY = 'MAIN/SET_SEARCH_QUERY',

  SEND_MAIL = 'MAIN/SEND_MAIL',

  SET_PROGRESS_TEXT = 'MAIN/SET_PROGRESS_TEXT',
}
